#
# Unix Makefile for couple. The list of 57 subroutines is
# correct, but it has not been tested. The may be some missing
# tab characters.
#
couple: couple.o \
	abortc.o amat.o backsub.o bathy.o bdf.o \
        bessj0.o bessy0.o bmat.o botdeps.o bounds.o \
	cdfun.o cdj0.o cdsrt.o cdtan.o cexib.o cexibd.o \
        cexiw.o cexiwb.o cexiwd.o chdh.o \
        choldc.o cjdj.o \
        clineqs.o cpres.o \
	crscup.o csds.o csymeig.o cupb.o \
	cupbw.o cupw.o cupwb.o cvmult.o cwns.o dreal.o \ 
	file.o foresub.o egnval.o galrkn.o gama0.o \
	gama00.o genabc.o header.o hk01.o hk02.o \  
	indep.o indexx.o input.o mgs.o mmult.o \ 
	propm.o prtmat.o prttl.o rcf.o rwprof.o \
	tmmult.o zcexib.o zcexiw.o
#
	f77 -o couple couple.o \
	abortc.o amat.o backsub.o bathy.o bdf.o \
        bessj0.o bessy0.o bmat.o botdeps.o bounds.o \
	cdfun.o cdj0.o cdsrt.o cdtan.o cexib.o cexibd.o \
        cexiw.o cexiwb.o cexiwd.o chdh.o \
        choldc.o cjdj.o \
        clineqs.o cpres.o \
	crscup.o csds.o csymeig.o cupb.o \
	cupbw.o cupw.o cupwb.o cvmult.o cwns.o dreal.o \ 
	file.o foresub.o egnval.o galrkn.o gama0.o \
	gama00.o genabc.o header.o hk01.o hk02.o \  
	indep.o indexx.o input.o mgs.o mmult.o \ 
	propm.o prtmat.o prttl.o rcf.o rwprof.o \
	tmmult.o zcexib.o zcexiw.o
#
couple.o: couple.f
	f77 -c couple.f
abortc.o: abortc.f
	f77 -c abortc.f
amat.o: amat.f 
	f77 -c amat.f
backsub.o: backsub.f 
	f77-c backsub.f
bathy.o: bathy.f 
	f77-c bathy.f
bdf.o: bdf.f 
	f77-c bdf.f
bessj0.o: bessj0.f 
	f77-c bessj0.f
bessy0.o: bessy0..f 
	f77-c bessy0..f
bmat.o: bmat.f 
	f77-c bmat.f
botdeps.o: botdeps.f
	f77-c botdeps.f
bounds.o: bounds.f 
	f77-c bounds.f
cdfun.o: cdfu.f
	f77-c cdfu.f
cdj0.o: .f
	f77-c cdj0.f
cdsrt.o: .f
	f77-c cdsrt.f
cdtan.o: cdtan.f
	f77-c cdtan.f
cexib.o: cexib.f
	f77-c cexib.f
cexibd.o: .f
	f77-c cexibd.f
cexiw.o: cexiw.f
	f77-c cexiw.f
cexiwb.o: cexiwb.f
	f77-c cexiwb.f
cexiwd.o: cexiwd.f
	f77-c cexiwd.f
chdh.o: chdh.f
	f77-c chdh.f
choldc.o: choldc.f
	f77-c choldc.f
cjdj.o: cjdj.f
	f77-c cjdj.f
clineqs.o: clineqs.f
	f77-c clineqs.f
cpres.o: cpres.f
	f77-c cpres.f
crscup.o: crscup.f
	f77-c crscup.f
csds.o: csds.f
	f77-c csds.f
csymeig.o: csymeig.f
	f77-c csymeig.f
cupb.o: cupb.f 
	f77-c cupb.f
cupbw.o: cupbw.f
	f77-c cupbw.f
cupw.o: cupw.f
	f77-c cupw.f
cupwb.o: cupwb.f
	f77-c cupwb.f
cvmult.o: cvmult.f
	f77-c cvmult.f
cwns.o: cwns.f
	f77-c cwns.f
dreal.o: dreal.f
	f77-c dreal.f
file.o: file.f
	f77-c file.f
foresub.o: foresub.f
	f77-c foresub.f
egnval.o: egnval.f
	f77-c egnval.f
galrkn.o: galrkn.f
	f77-c galrkn.f
gama0.o: gama0.f
	f77-c gama0.f
gama00.o: gama00.f
	f77-c gama00.f
genabc.o: genabc.f
	f77-c genabc.f
header.o: header.f
	f77-c header.f
hk01.o: hk01.f
	f77-c hk01.f
hk02.o: hk02.f
	f77-c hk02.f
indep.o: indep.f
	f77-c indep.f
indexx.o: indexx.f
	f77-c indexx.f
input.o: input.f
	f77-c input.f
mgs.o: mgs.f
	f77-c mgs.f
mmult.o: mmult.f
	f77-c mmult.f
propm.o: propm.f
	f77-c propm.f
prtmat.o: prtmat.f
	f77-c prtmat.f
prttl.o: prttl.f
	f77-c prttl.f
rcf.o: rcf.f
	f77-c rcf.f
rwprof.o: rwprof.f
	f77-c rwprof.f
tmmult.o: tmmult.f
	f77-c tmmult.f
zcexib.o: zcexib.f
	f77-c zcexib.f
zcexiw.o: zcexiw.f
	f77-c zcexiw.f
